# Generated by Django 5.2.3 on 2025-07-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blognote",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество просмотров"
            ),
        ),
    ]
